image:
  registry: "CHANGEME.dkr.ecr.eu-west-2.amazonaws.com"
  repository: "laa-data-user-api"
  tag: "latest"
ingress:
  className: "default"
  host: "laa-data-user-api.internal.cloud-platform.service.justice.gov.uk"
