azureAppUri: "api://devlexternal.onmicrosoft.com/laa-data-user-api"
ingress:
  className: "modsec-non-prod"
  host: "laa-data-user-api-dev.cloud-platform.service.justice.gov.uk"
allowlist:
  enabled: true
  groups: "internal staff;internal cp;external staff;external nat cp"
