replicaCount: 3
springProfile: "local"
techServicesAzureScope: ""
techServicesAzureClientId: ""
techServicesTenantId: ""
techServicesAzureClientSecret: ""
techServicesBaseUrl: ""
sentryEnvironment: "local"
sentryDsn: ""
image:
  repository: "laa-data-user-api"
  tag: "latest"
ingress:
  className: "default"
  host: "laa-data-user-api.internal.cloud-platform.service.justice.gov.uk"
  enableModSecurity: false
allowlist:
  enabled: false
  cidr: ""
  groups: ""
resources:
  requests:
    memory: "1200Mi"
    cpu: "300m"
  limits:
    memory: "3000Mi"
    cpu: "1"
grafanaDashboard:
  name: ""
  namespace: ""
