plugins {
    id 'uk.gov.justice.service.laa.laa-java-gradle-plugin' version '3.0.0'
    id 'uk.gov.justice.service.laa.laa-spring-boot-gradle-plugin' version '3.0.0'
    id "io.sentry.jvm.gradle" version "6.15.0"
}

group = 'uk.gov.justice.laa'
version = '0.0.1-SNAPSHOT'

ext {
    springDocVersion = "3.0.0"
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springDocVersion}"
    implementation 'tools.jackson.dataformat:jackson-dataformat-csv:3.0.3'
    implementation 'io.sentry:sentry-spring-boot-4:8.43.2'
    implementation('com.azure.spring:spring-cloud-azure-starter-active-directory:7.3.0') {
        exclude group: 'org.springframework.boot', module: 'spring-boot-jackson2'
        exclude group: 'com.fasterxml.jackson.core'
    }
    implementation 'com.azure:azure-identity'

    // Utilities & Core Framework Enhancements
    implementation 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'org.apache.httpcomponents.client5:httpclient5'

    runtimeOnly 'org.springframework.boot:spring-boot-properties-migrator'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
    testLogging {
        showStandardStreams = true
        events "failed", "skipped", "standard_out", "standard_error"
    }
}
