spring:
  application:
    name: laa-data-user-api

  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_ADDRESS:localhost}:5432/${POSTGRES_DB_NAME}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/${AZURE_TENANT_ID}/
          jwk-set-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/discovery/v2.0/keys
          audience: ${AZURE_CLIENT_ID}

azure:
  tenant-id: ${AZURE_TENANT_ID}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
