apiVersion: apps/v1
kind: Deployment
metadata:
  name: laa-data-user-api
  labels:
    app: laa-data-user-api
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: laa-data-user-api
  template:
    metadata:
      labels:
        app: laa-data-user-api
    spec:
      securityContext:
        runAsUser: 10000
        runAsNonRoot: true
      automountServiceAccountToken: false # Prevents the default service account token from being mounted, which is a security best practice when using IRSA
      containers:
        - name: laa-data-user-api
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          securityContext:
            runAsUser: 10000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILE
              value: {{ .Values.springProfile }}
            - name: TECH_SERVICES_AZURE_SCOPE
              value: {{ .Values.techServicesAzureScope }}
            - name: TECH_SERVICES_AZURE_CLIENT_ID
              value: {{ .Values.techServicesAzureClientId }}
            - name: TECH_SERVICES_TENANT_ID
              value: {{ .Values.techServicesTenantId }}
            - name: TECH_SERVICES_AZURE_CLIENT_SECRET
              value: {{ .Values.techServicesAzureClientSecret }}
            - name: TECH_SERVICES_BASE_URL
              value: {{ .Values.techServicesBaseUrl }}
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: laa-data-user-api-azure-tenant-secret-k8s
                  key: AZURE_TENANT_ID
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: laa-data-user-api-azure-client-id-k8s
                  key: AZURE_CLIENT_ID
            - name: SENTRY_DSN
              value: {{ .Values.sentryDsn }}
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.sentryEnvironment }}
            - name: SENTRY_ENABLED
              value: {{ .Values.sentryEnabled }}
            - name: SENTRY_SAMPLE_RATE
              value: {{ .Values.sentrySampleRate }}
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_password
            - name: POSTGRES_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_name
            - name: POSTGRES_DB_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: rds_instance_address
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 15
            periodSeconds: 10
