{
 "title": "LAA Data User API (dev) dashboard",
 "tags": [
  "dev",
  "Authz",
  "LASSIE",
  "IDAM",
  "LAA",
  "LAA Data User API"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cwdatasource", "label": "Cloudwatch Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "dbinstanceidentifier",
    "query": "cloud-platform-faeb1d14a7275a64"
   },
   { "name": "cpnamespace", "query": "laa-data-user-api-dev" }
  ]
 },
 "panels": [
  { "title": "HTTP Request Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(http_server_requests_seconds_count{namespace='${cpnamespace}'}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Requests Per Instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(http_server_requests_seconds_count{namespace='${cpnamespace}',status=~'2..'}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Requests per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "sum by(uri) (increase(http_server_requests_seconds_count{namespace='${cpnamespace}', uri!~'.*health.*', status=~'2..'}[$__rate_interval])) ",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  { "title": "HTTP Error Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "HTTP Code 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace = \"${cpnamespace}\",status=~\"4.*\"}[5m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Code 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace = \"${cpnamespace}\",status=~\"5.*\"}[5m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Server Response Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Average Response Time Per URI",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(uri) (rate(http_server_requests_seconds_sum{namespace='${cpnamespace}', uri!~'.*health.*', status=~'2..'}[$__rate_interval])) / sum by(uri) (rate(http_server_requests_seconds_count{namespace='${cpnamespace}', uri!~'.*health.*', status=~'2..'}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Response Time Per URI",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(uri) (http_server_requests_seconds_max{namespace='${cpnamespace}', uri!~'.*health.*', status=~'2..'}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Pod Info",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace='${cpnamespace}',pod=~'.*laa-data-user-api.*'})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum({namespace='${cpnamespace}',phase='Running',pod=~'.*laa-data-user-api.*'} + 0)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum({namespace='${cpnamespace}',phase='Pending',pod=~'.*laa-data-user-api.*'} + 0)",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum({namespace='${cpnamespace}',phase='Failed',pod=~'.*laa-data-user-api.*'} + 0)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 2, "y": 32 },
   "targets": [
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_receive_bytes_total{namespace='${cpnamespace}'}[5m]))))",
     "legendFormat": "Average Bytes Received"
    },
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace='${cpnamespace}'}[5m]))))",
     "legendFormat": "Average Bytes Transmitted"
    }
   ]
  },
  {
   "title": "Resource quota",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * kube_resourcequota{job=\"kube-state-metrics\", type=\"used\", namespace=\"${cpnamespace}\"}\n/ ignoring(instance, job, type)\n(kube_resourcequota{job=\"kube-state-metrics\", type=\"hard\", namespace=\"${cpnamespace}\"} > 0)",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "ECR Image count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 32 },
   "targets": [
    {
     "expr": "sum(aws_ecr_repository_image_count{repository_name=~'laa-portal-stabilisation-tech/${cpnamespace}'}) by (repository_name)",
     "legendFormat": "ECR Image Count"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Percentage of container memory requested",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(container_memory_working_set_bytes{image!='',namespace='${cpnamespace}',pod=~\"laa-data-user-api.*\"}) by (container, pod)\n      /\n    sum(kube_pod_container_resource_requests{resource='memory', namespace='${cpnamespace}',pod=~\"laa-data-user-api.*\"} > 0) by (container, pod)\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Percentage of container memory limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(container_memory_working_set_bytes{image!=\"\", namespace='${cpnamespace}', pod=~\"laa-data-user-api.*\"}) by (container, pod)\n      /\n    sum(kube_pod_container_resource_limits{namespace='${cpnamespace}', pod=~\"laa-data-user-api.*\",resource=\"memory\"} > 0) by (container, pod)\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"${cpnamespace}\", pod=~'laa-data-user-api.*'}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "container_memory_max_usage_bytes{namespace=\"${cpnamespace}\", pod=~'laa-data-user-api.*'}",
     "legendFormat": "{{pod}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Percentage of CPU request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(\n      rate(container_cpu_usage_seconds_total{namespace='${cpnamespace}', pod=~\"laa-data-user-api.*\"}[5m])\n    ) by (pod, container, namespace)\n      /\n    sum(\n      kube_pod_container_resource_limits{namespace='${cpnamespace}', pod=~'laa-data-user-api.*', resource='cpu'}\n    ) by (pod, container, namespace)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(\n      rate(container_cpu_usage_seconds_total{namespace='${cpnamespace}', pod=~\"laa-data-user-api.*\"}[5m])\n    ) by (pod, container, namespace)\n      /\n    sum(\n      kube_pod_container_resource_limits{namespace='${cpnamespace}', pod=~\"laa-data-user-api.*\",resource='cpu'}\n    ) by (pod, container, namespace)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Per Instance",
   "type": "timeseries",
   "description": "Top 3 CPU Used Per Instance",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "topk(3, max by (pod, container)(rate(container_cpu_usage_seconds_total{image!='', namespace='${cpnamespace}',pod=~\"laa-data-user-api.*\"}[$__rate_interval]))) / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Metrics: active threads & queue size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "sum(executor_active_threads{namespace=\"${cpnamespace}\"})",
     "legendFormat": "Number of threads actively executing tasks"
    },
    {
     "expr": "sum(executor_pool_max_threads{namespace=\"${cpnamespace}\"})",
     "legendFormat": "The maximum allowed number of threads in the pool"
    }
   ]
  },
  { "title": "JVM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Max Survivor",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{namespace='${cpnamespace}',area='heap',id='Survivor Space'} / 1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Survivor Space (MB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 2, "y": 72 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace='${cpnamespace}',area='heap',id='Survivor Space'}/1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Eden",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 2, "x": 8, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{namespace='${cpnamespace}',area='heap',id='Eden Space'}/1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Eden Space (MB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 10, "y": 72 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace='${cpnamespace}',area='heap',id='Eden Space'}/1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Tenured",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 2, "x": 16, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{namespace='${cpnamespace}',area='heap',id='Tenured Gen'} /1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Tenured Gen (MB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 72 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace='${cpnamespace}',area='heap',id='Tenured Gen'} /1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "PDA Sync Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Last Sync Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pda_sync_last_status{namespace='${cpnamespace}',source='scheduler'}) by (namespace)",
     "legendFormat": "Last Sync Status"
    }
   ]
  },
  {
   "title": "Last Sync Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(pda_sync_last_duration_seconds{namespace='${cpnamespace}',source='scheduler'}) by (namespace)",
     "legendFormat": "Duration (seconds)"
    }
   ]
  },
  {
   "title": "Last Sync Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(pda_sync_last_errors{namespace='${cpnamespace}',source='scheduler'}) by (namespace)",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Last Sync - Firm Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(pda_sync_last_firms_created{namespace='${cpnamespace}',source='scheduler'}) by (namespace)",
     "legendFormat": "Created"
    },
    {
     "expr": "max(pda_sync_last_firms_updated{namespace='${cpnamespace}',source='scheduler'}) by (namespace)",
     "legendFormat": "Updated"
    },
    {
     "expr": "max(pda_sync_last_firms_disabled{namespace='${cpnamespace}',source='scheduler'}) by (namespace)",
     "legendFormat": "Disabled"
    }
   ]
  },
  {
   "title": "Last Sync - Office Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(pda_sync_last_offices_created{namespace='${cpnamespace}',source='scheduler'}) by (namespace)",
     "legendFormat": "Created"
    },
    {
     "expr": "max(pda_sync_last_offices_updated{namespace='${cpnamespace}',source='scheduler'}) by (namespace)",
     "legendFormat": "Updated"
    },
    {
     "expr": "max(pda_sync_last_offices_deleted{namespace='${cpnamespace}',source='scheduler'}) by (namespace)",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Sync Success/Failure Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pda_sync_success_total{namespace='${cpnamespace}',source='scheduler'}[5m]))",
     "legendFormat": "Success Rate"
    },
    {
     "expr": "sum(rate(pda_sync_failure_total{namespace='${cpnamespace}',source='scheduler'}[5m]))",
     "legendFormat": "Failure Rate"
    }
   ]
  },
  {
   "title": "Cumulative Operations (1h increase)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(pda_sync_firms_created_total{namespace='${cpnamespace}',source='scheduler'}[1h])",
     "legendFormat": "Firms Created"
    },
    {
     "expr": "increase(pda_sync_firms_updated_total{namespace='${cpnamespace}',source='scheduler'}[1h])",
     "legendFormat": "Firms Updated"
    },
    {
     "expr": "increase(pda_sync_firms_disabled_total{namespace='${cpnamespace}',source='scheduler'}[1h])",
     "legendFormat": "Firms Disabled"
    },
    {
     "expr": "increase(pda_sync_offices_created_total{namespace='${cpnamespace}',source='scheduler'}[1h])",
     "legendFormat": "Offices Created"
    },
    {
     "expr": "increase(pda_sync_offices_updated_total{namespace='${cpnamespace}',source='scheduler'}[1h])",
     "legendFormat": "Offices Updated"
    },
    {
     "expr": "increase(pda_sync_offices_deleted_total{namespace='${cpnamespace}',source='scheduler'}[1h])",
     "legendFormat": "Offices Deleted"
    }
   ]
  },
  { "title": "PostgreSQL database (RDS)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "CPUUtilization/FailedSQLServerAgentJobsCount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FailedSQLServerAgentJobsCount",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DatabaseConnections/DiskQueueDepth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "FreeableMemory/FreeStorageSpace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ReadIOPS/WriteIOPS/BurstBalance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BurstBalance",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ReadLatency/WriteLatency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ReadThroughput/WriteThroughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NetworkReceiveThroughput/NetworkTransmitThroughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "SwapUsage/BinLogDiskUsage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SwapUsage",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BinLogDiskUsage",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPUCreditUsage/CPUCreditBalance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CPUCreditUsage",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "OldestReplicationSlotLag/ReplicaLag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "OldestReplicationSlotLag",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReplicaLag",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ReplicationSlotDiskUsage/TransactionLogsDiskUsage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReplicationSlotDiskUsage",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TransactionLogsDiskUsage",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "MaximumUsedTransactionIDs/TransactionLogsGeneration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "MaximumUsedTransactionIDs",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "$dbinstanceidentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TransactionLogsGeneration",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}