name: Deploy Dev

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write
  actions: read
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ecr:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build JAR
        run: ./gradlew build -x test
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Assume role in Cloud Platform
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}

      # Login to container repository
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CERT }}" > ca.crt
          kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
          kubectl config set-credentials deploy-user --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${KUBE_NAMESPACE}
          kubectl config use-context ${KUBE_CLUSTER}
        env:
          KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
          KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}

      - name: Build and Push Docker Image to the container repository
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .

          # Tag the image per env (links with lifecycle policy of image)
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$ENV_NAME

          # Push the image to the ECR repository
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$ENV_NAME
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
          ENV_NAME: ${{ vars.ENV_NAME }}

      - name: Generate Deployment Files
        run: |
          # Get all env vars, filter out server_protocol, uri and http1_reject, and format with leading dollar signs
          ALLOWED_VARS=$(printenv | cut -d= -f1 | grep -v -E '^(server_protocol|uri|http1_reject)$' | sed 's/^/$/' | tr '\n' ' ')
          
          # Pass the dynamic list into envsubst for all templates
          if [ -d "deployment/templates" ]; then
            for template in deployment/templates/*.yml; do
              filename=$(basename -- "$template")
              envsubst "$ALLOWED_VARS" < "$template" > "deployment/$filename"
            done
          else
            echo "Warning: deployment/templates directory not found. Assuming manifests are already rendered."
          fi
        env:
          IMAGE_TAG: ${{ github.sha }}
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
          ENV_NAME: ${{ vars.ENV_NAME }}
          INGRESS_CLASS_NAME: ${{ vars.INGRESS_CLASS_NAME }}

      - name: Deploy to Cloud Platform
        run: |
          kubectl -n ${KUBE_NAMESPACE} apply -f deployment/
        env:
          KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}

      - name: Wait for new deployment to finish
        run: |
          kubectl -n ${KUBE_NAMESPACE} rollout status deployment laa-data-user-api --timeout=7m
        env:
          KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
