name: TruffleHog secret scan

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
  push:
  schedule:
    - cron: "58 0 * * *" # run once a day at 00:58 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
    - name: TruffleHog scan
      uses: trufflesecurity/trufflehog@20652fbbdefffcdaa493a5bf57ab2ac6b1db715b # 3.97.1
      with:
        version: 3.96.0@sha256:aa821cf4ace8861c7d096d83818cdf7bb9719028a52d37a52eaad44086a52577
        extra_args: --results=verified
